### ISSUE TITLE
Failed to make complete framebuffer object 

### ISSUE THREAD

**Issue by sairasamdanii** [kimsungwhee/MosaicCamera#1]
I'm using KSHMosaicCamera in my project. While using KSHCameraController for four to five times, it start giving log "Failed to make complete framebuffer object ", and shows white blank screen. First time, I load controller, it appears fastly. I take a picture. Dismiss Controller. Next time, it appears a bit slow, then slower, more slower and finally after some attempts, it starts throwing warning and gives blank white screen.
My project is in a very critical stage. Can you please help me with this.

**Comment by kimsungwhee** [comment]
I can not see your source code, I do not a good judge.I think perhaps a memory leak in KSHCameraController，
